version: "3.9"

services:
  fakedatagen:
    build:
      context: .
      dockerfile: Api/FakeDataGen.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
